<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="minidrone" nsURI="http://www.obeo.fr/dsl/minidrone/1.0.0" nsPrefix="minidrone">
  <eClassifiers xsi:type="ecore:EClass" name="MiniDroneProgram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represent a program allowing to pilot a minidrone (Jumping Sumo or Rolling Spider)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//AbstractInstruction" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The referenced instructions contained in a program."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minidroneName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speedPercentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volumePercentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="audioMode" eType="#//AudioMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postureMode" eType="#//PostureMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true" interface="true"
      eSuperTypes="#//AbstractInstruction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represent a program instruction used to send command to the minidrone."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Straight" eSuperTypes="#//Instruction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A program instruction which send go backward/forward command to the minidrone."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The distance of movement."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Turn" eSuperTypes="#//Instruction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A program instruction which send a turn command to the minidrone."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The rotation angle."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Jump" eSuperTypes="#//Instruction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A program instruction which send a jump command to the minidrone. This command is specific to the Jumping Sumo."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//JumpMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The height of the jump."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JumpMode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Enumeration of jump types (only for Jumping Sumo)"/>
    </eAnnotations>
    <eLiterals name="LONG"/>
    <eLiterals name="HIGH" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PostureMode">
    <eLiterals name="JUMPER"/>
    <eLiterals name="KICKER" value="1"/>
    <eLiterals name="AUTOBALANCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AudioMode">
    <eLiterals name="MONSTER"/>
    <eLiterals name="INSECT" value="1"/>
    <eLiterals name="ROBOT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TakePicture" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="RecordVideo" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speed" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Posture" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//PostureMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volume" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timer" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//AbstractInstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//AbstractInstruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInstruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Animation" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//AnimationMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnimationMode">
    <eLiterals name="SPIN"/>
    <eLiterals name="TOUCH" value="1"/>
    <eLiterals name="SHAKE" value="2" literal="SHAKE"/>
    <eLiterals name="METRONOME" value="3"/>
    <eLiterals name="WAVE" value="4"/>
    <eLiterals name="SPINJUMP" value="5"/>
    <eLiterals name="SLALOM" value="6"/>
    <eLiterals name="SPINPOSTURE" value="7" literal="SPINPOSTURE"/>
    <eLiterals name="SPIRAL" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audio" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//AudioMode"/>
  </eClassifiers>
</ecore:EPackage>
